package com.igs.nfc_rw.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val primaryLight = Color(0xFF2196F3)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFBBDEFB)
val onPrimaryContainerLight = Color(0xFF0D47A1)

val secondaryLight = Color(0xFF03A9F4)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB3E5FC)
val onSecondaryContainerLight = Color(0xFF01579B)

val tertiaryLight = Color(0xFF00BCD4)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB2EBF2)
val onTertiaryContainerLight = Color(0xFF006064)

val errorLight = Color(0xFFB00020)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFCD8DF)
val onErrorContainerLight = Color(0xFF690005)

val backgroundLight = Color(0xFFF5F5F5)
val onBackgroundLight = Color(0xFF000000)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF000000)
val surfaceVariantLight = Color(0xFFEEEEEE)
val onSurfaceVariantLight = Color(0xFF757575)

val outlineLight = Color(0xFFBDBDBD)
val outlineVariantLight = Color(0xFFE0E0E0)
val scrimLight = Color(0x99000000)

val inverseSurfaceLight = Color(0xFF121212)
val inverseOnSurfaceLight = Color(0xFFFFFFFF)
val inversePrimaryLight = Color(0xFF90CAF9)

val surfaceDimLight = Color(0xFFE0E0E0)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF5F5F5)
val surfaceContainerLight = Color(0xFFEEEEEE)
val surfaceContainerHighLight = Color(0xFFE8E8E8)
val surfaceContainerHighestLight = Color(0xFFE3E3E3)

// Dark theme colors
val primaryDark = Color(0xFF90CAF9)
val onPrimaryDark = Color(0xFF000000)
val primaryContainerDark = Color(0xFF0D47A1)
val onPrimaryContainerDark = Color(0xFFBBDEFB)

val secondaryDark = Color(0xFF81D4FA)
val onSecondaryDark = Color(0xFF000000)
val secondaryContainerDark = Color(0xFF01579B)
val onSecondaryContainerDark = Color(0xFFB3E5FC)

val tertiaryDark = Color(0xFF4DD0E1)
val onTertiaryDark = Color(0xFF000000)
val tertiaryContainerDark = Color(0xFF006064)
val onTertiaryContainerDark = Color(0xFFB2EBF2)

val errorDark = Color(0xFFCF6679)
val onErrorDark = Color(0xFF000000)
val errorContainerDark = Color(0xFF690005)
val onErrorContainerDark = Color(0xFFFCD8DF)

val backgroundDark = Color(0xFF121212)
val onBackgroundDark = Color(0xFFFFFFFF)
val surfaceDark = Color(0xFF121212)
val onSurfaceDark = Color(0xFFFFFFFF)
val surfaceVariantDark = Color(0xFF424242)
val onSurfaceVariantDark = Color(0xFFBDBDBD)

val outlineDark = Color(0xFF757575)
val outlineVariantDark = Color(0xFF424242)
val scrimDark = Color(0x99000000)

val inverseSurfaceDark = Color(0xFFF5F5F5)
val inverseOnSurfaceDark = Color(0xFF000000)
val inversePrimaryDark = Color(0xFF0D47A1)

val surfaceDimDark = Color(0xFF121212)
val surfaceBrightDark = Color(0xFF383838)
val surfaceContainerLowestDark = Color(0xFF000000)
val surfaceContainerLowDark = Color(0xFF1E1E1E)
val surfaceContainerDark = Color(0xFF242424)
val surfaceContainerHighDark = Color(0xFF2E2E2E)
val surfaceContainerHighestDark = Color(0xFF383838)

val primaryLightMediumContrast = Color(0xFF303066)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF6867A1)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF353448)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF6C6B81)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF303066)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF6767A2)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFCF8FF)
val onBackgroundLightMediumContrast = Color(0xFF1B1B21)
val surfaceLightMediumContrast = Color(0xFFFCF8FF)
val onSurfaceLightMediumContrast = Color(0xFF111116)
val surfaceVariantLightMediumContrast = Color(0xFFE4E1EC)
val onSurfaceVariantLightMediumContrast = Color(0xFF36353E)
val outlineLightMediumContrast = Color(0xFF53515B)
val outlineVariantLightMediumContrast = Color(0xFF6D6C75)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF303036)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF3EFF7)
val inversePrimaryLightMediumContrast = Color(0xFFC2C1FF)
val surfaceDimLightMediumContrast = Color(0xFFC8C5CD)
val surfaceBrightLightMediumContrast = Color(0xFFFCF8FF)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF6F2FA)
val surfaceContainerLightMediumContrast = Color(0xFFEAE7EF)
val surfaceContainerHighLightMediumContrast = Color(0xFFDFDBE3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD3D0D8)

val primaryLightHighContrast = Color(0xFF26255C)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF44437B)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF2B2A3D)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF48475B)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF26255C)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF43437B)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFCF8FF)
val onBackgroundLightHighContrast = Color(0xFF1B1B21)
val surfaceLightHighContrast = Color(0xFFFCF8FF)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE4E1EC)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2C2B34)
val outlineVariantLightHighContrast = Color(0xFF494851)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF303036)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFC2C1FF)
val surfaceDimLightHighContrast = Color(0xFFBAB7BF)
val surfaceBrightLightHighContrast = Color(0xFFFCF8FF)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF3EFF7)
val surfaceContainerLightHighContrast = Color(0xFFE5E1E9)
val surfaceContainerHighLightHighContrast = Color(0xFFD6D3DB)
val surfaceContainerHighestLightHighContrast = Color(0xFFC8C5CD)

val primaryDarkMediumContrast = Color(0xFFDBD9FF)
val onPrimaryDarkMediumContrast = Color(0xFF1F1E55)
val primaryContainerDarkMediumContrast = Color(0xFF8C8BC8)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFDCDAF3)
val onSecondaryDarkMediumContrast = Color(0xFF242436)
val secondaryContainerDarkMediumContrast = Color(0xFF908EA5)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFDBD9FF)
val onTertiaryDarkMediumContrast = Color(0xFF1F1F55)
val tertiaryContainerDarkMediumContrast = Color(0xFF8B8BC8)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF131318)
val onBackgroundDarkMediumContrast = Color(0xFFE5E1E9)
val surfaceDarkMediumContrast = Color(0xFF131318)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF47464F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDEDBE6)
val outlineDarkMediumContrast = Color(0xFFB3B0BB)
val outlineVariantDarkMediumContrast = Color(0xFF918F99)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE5E1E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A292F)
val inversePrimaryDarkMediumContrast = Color(0xFF424279)
val surfaceDimDarkMediumContrast = Color(0xFF131318)
val surfaceBrightDarkMediumContrast = Color(0xFF45444A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF07070C)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1D23)
val surfaceContainerDarkMediumContrast = Color(0xFF28272D)
val surfaceContainerHighDarkMediumContrast = Color(0xFF333238)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3D43)

val primaryDarkHighContrast = Color(0xFFF1EEFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFBEBDFD)
val onPrimaryContainerDarkHighContrast = Color(0xFF04003B)
val secondaryDarkHighContrast = Color(0xFFF1EEFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC2C0D9)
val onSecondaryContainerDarkHighContrast = Color(0xFF09091B)
val tertiaryDarkHighContrast = Color(0xFFF1EEFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFBDBDFD)
val onTertiaryContainerDarkHighContrast = Color(0xFF03003B)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF131318)
val onBackgroundDarkHighContrast = Color(0xFFE5E1E9)
val surfaceDarkHighContrast = Color(0xFF131318)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF47464F)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF2EEFA)
val outlineVariantDarkHighContrast = Color(0xFFC4C1CC)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE5E1E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF424279)
val surfaceDimDarkHighContrast = Color(0xFF131318)
val surfaceBrightDarkHighContrast = Color(0xFF504F56)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1F1F25)
val surfaceContainerDarkHighContrast = Color(0xFF303036)
val surfaceContainerHighDarkHighContrast = Color(0xFF3C3B41)
val surfaceContainerHighestDarkHighContrast = Color(0xFF47464C)









